# Mainnet preset - Capella


# Withdrawals processing
# ---------------------------------------------------------------
# 2**14 (= 16,384) withdrawals
MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP: 16384


# Max operations per block
# ---------------------------------------------------------------
# 2**4 (= 16)
MAX_BLS_TO_EXECUTION_CHANGES: 16


# Execution
# ---------------------------------------------------------------
# 2**4 (= 16) withdrawals
MAX_WITHDRAWALS_PER_PAYLOAD: 16
