version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: protolambda/zrnt-ci-primary:1.5.0
    working_directory: /zrnt-repo

    parallelism: 2

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Check formatting
          command: "! go fmt ./... 2>&1 | read"

      - restore_cache:
          keys:
            - spec-tests-v0_10_1

      - run:
          name: Update spec tests cache
          command: make download-tests

      - run:
          name: Run unit tests and generate coverage reports
          command: TEST_OUT_DIR=$TEST_RESULTS make test

      - save_cache:
          key: spec-tests-v0_10_1
          paths:
            - tests/spec/eth2.0-spec-tests

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - codecov/upload:
          file: /tmp/test-results/coverage.out

      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
